-- Database: hospital_db

CREATE TABLE corporations (
                              id BIGINT PRIMARY KEY,
                              name VARCHAR(200),
                              active BOOLEAN
);

CREATE TABLE employees (
                           id BIGINT PRIMARY KEY,
                           corporation_id BIGINT,
                           name VARCHAR(200),
                           email VARCHAR(200),
                           active BOOLEAN,
                           employee_id BIGINT,
                           corporation_name VARCHAR(255),
                           employee_name VARCHAR(255),
                           CONSTRAINT fk_employee FOREIGN KEY (corporation_id)
                               REFERENCES corporations(id)
);

CREATE TABLE hospitals (
                           id BIGINT PRIMARY KEY,
                           name VARCHAR(200),
                           opening_time TIME,
                           closing_time TIME,
                           active BOOLEAN,
                           hospital_id BIGINT,
                           hospital_name VARCHAR(255)
);

CREATE TABLE patients (
                          patient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255),
                          age INTEGER NOT NULL,
                          gender VARCHAR(255),
                          phone VARCHAR(255)
);

CREATE TABLE appointments (
                              id BIGINT PRIMARY KEY,
                              employee_id BIGINT,
                              hospital_id BIGINT,
                              appointment_date DATE,
                              slot_time TIME,
                              status VARCHAR(255),
                              appointment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              CONSTRAINT fk_employee FOREIGN KEY (employee_id)
                                  REFERENCES employees(id),
                              CONSTRAINT fk_hospital FOREIGN KEY (hospital_id)
                                  REFERENCES hospitals(id)
);

-- Sample data

INSERT INTO corporations (id, name, active) VALUES
                                                (1, 'Infosys', true),
                                                (2, 'Uno.care', true),
                                                (3, 'Accenture', true);

INSERT INTO employees (id, corporation_id, name, email, active, employee_id, corporation_name, employee_name) VALUES
                                                                                                                  (1, 1, 'Rahul Sharma', 'rahul@gmail.com', true, 1, 'Infosys', 'Rahul Sharma'),
                                                                                                                  (2, 2, 'Rakesh Rai', 'rakesh@gmail.com', true, 2, 'Uno.care', 'Rakesh Rai'),
                                                                                                                  (3, 3, 'Harsh Verma', 'harsh@gmail.com', true, 3, 'Accenture', 'Harsh Verma');

INSERT INTO hospitals (id, name, opening_time, closing_time, active, hospital_id, hospital_name) VALUES
                                                                                                     (1, 'Fortis Hospital', '08:00:00', '20:00:00', true, 1, 'Fortis Hospital'),
                                                                                                     (2, 'AIIMS Delhi', '07:00:00', '22:00:00', true, 2, 'AIIMS Delhi'),
                                                                                                     (3, 'Apollo Hospital', '09:00:00', '18:00:00', true, 3, 'Apollo Hospital');